Update rsp.yaml
ONDC-Official/protocol-network-extension pull request #15
Opened 2022-09-26 09:24 UTC by AbhiSIITR

Added - rsp_uri and rsp_id

2022-09-26 09:26 UTC, nitinmish reviewed
These are required for addition of RSP URI and RSP ID as the receiver and settlement agency will need to post the responses on /on_recon.

2022-09-26 09:26 UTC, nitinmish approved these changes

2022-10-04 04:26 UTC, BLR-0118 requested changes
rsp_id and rsp_uri will be in the Context

2022-10-04 10:56 UTC, AbhiSIITR commented
Noted.

2022-10-04 10:56 UTC, closed without merging